----- DERS 307 Database Oluþturma
CREATE DATABASE Udemy
DROP DATABASE Udemy

----- DERS 308 Database Oluþturma
----- YEDEK ALMA DATABASE BACKUP RESTORE

----- DERS 309 Tablo Oluþturma Düzenleme
CREATE TABLE Diger
(	ID INT,
	isim NVARCHAR(255),
	soyisim NVARCHAR(255)
)

----- DERS 310 Tablo Oluþturma Düzenleme II

ALTER TABLE Diger
	ADD olusturmaTarihi DateTime

ALTER TABLE Diger
	DROP COLUMN OlusturmaTarihi

ALTER TABLE Diger
	ALTER COLUMN isim NVARCHAR(300)

DROP TABLE Diger

----- DERS 311 Kýsýtlayýcý Nedir 
--NOT NULL

CREATE TABLE CONSTRAINT_NOTNULL
( 
ID INT NOT NULL,
ISIM NVARCHAR(50),
SOYISIM NVARCHAR(50) NOT NULL
)

----- DERS 313
--UNIQE

CREATE TABLE CONSTRAINT_UNIQUE
( 
ID INT NOT NULL UNIQUE,
ISIM NVARCHAR(50),
SOYISIM NVARCHAR(50) NOT NULL,
EMAIL NVARCHAR(25) UNIQUE
)

----- DERS 314
--PRIMARY KEY

CREATE TABLE CONSTRAINT_PRIMARYKEY
( 
ID INT PRIMARY KEY,
ISIM NVARCHAR(50),
SOYISIM NVARCHAR(50),
EMAIL NVARCHAR(25) UNIQUE
)

----- DERS 315
--CHECK

CREATE TABLE CONSTRAINT_CHECK
( 
ID INT PRIMARY KEY,
ISIM NVARCHAR(50),
SOYISIM NVARCHAR(50),
YAS INT NOT NULL CHECK(YAS >=15)
)

----- DERS 316
--DEFAULT

CREATE TABLE CONSTRAINT_DEFAULT
( 
ID INT PRIMARY KEY,
ISIM NVARCHAR(50) DEFAULT 'Unknown',
SOYISIM NVARCHAR(50),
TARIH DATETIME DEFAULT GETDATE()
)

----- DERS 317
--FOREIGN KEY

CREATE TABLE musteri
( 
ID INT PRIMARY KEY,
MUSTERI_NO INT,
TCKNO NVARCHAR(11),
VKN NVARCHAR(13),
ISIM NVARCHAR(50) DEFAULT 'Unknown',
SOYISIM NVARCHAR(50),
TARIH DATETIME
)


CREATE TABLE m_iletisim
(
ID INT PRIMARY KEY,
MUSTERI_ID INT,
TYPE INT,
DEGER NVARCHAR(500),
TARIH DATETIME
FOREIGN KEY (MUSTERI_ID) REFERENCES musteri(ID)
)

----- DERS 318
--INSERT, UPDATE, DELETE


SELECT * FROM musteri

INSERT INTO musteri (ID, MUSTERI_NO, TCKNO, ISIM) VALUES (5, 69, 4323252523, 'BAHRÝYE')

UPDATE musteri SET 
	VKN		= '4545', 
	SOYISIM = 'ERDOÐAN'
WHERE ID = 5

DELETE musteri WHERE ID = 5
